---
version: '3.8'
# start postgres DB server only
services:
  to-postgres:
    container_name: as-postgres
    image: postgres:14.1-alpine
#    networks:
#      - as-network
    restart: always
    environment:
      - POSTGRES_USER=as_2024
      - POSTGRES_PASSWORD=2024_as_2024
    ports:
      - '5432:5432'
#    volumes:
#      - db:/var/lib/postgresql/data
#volumes:
#  db:
#    driver: local
#networks:
#  as-network:
#    name: as-network
...